//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.09 at 03:56:25 PM MESZ 
//


package org.openfuxml.addon.jsf.data.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openfuxml.org/jsf}listing" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.openfuxml.org}absatz-ohne" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listing",
    "absatzOhne"
})
@XmlRootElement(name = "example")
public class Example {

    @XmlElement(required = true)
    protected List<Listing> listing;
    @XmlElement(name = "absatz-ohne", namespace = "http://www.openfuxml.org", required = true)
    protected List<AbsatzOhne> absatzOhne;
    @XmlAttribute
    protected String title;

    /**
     * Gets the value of the listing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Listing }
     * 
     * 
     */
    public List<Listing> getListing() {
        if (listing == null) {
            listing = new ArrayList<Listing>();
        }
        return this.listing;
    }

    /**
     * Gets the value of the absatzOhne property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the absatzOhne property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbsatzOhne().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbsatzOhne }
     * 
     * 
     */
    public List<AbsatzOhne> getAbsatzOhne() {
        if (absatzOhne == null) {
            absatzOhne = new ArrayList<AbsatzOhne>();
        }
        return this.absatzOhne;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
