//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 12:24:19 PM MEZ 
//


package org.openfuxml.addon.wiki.data.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.addon.wiki.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.addon.wiki.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ofx }
     * 
     */
    public Ofx createOfx() {
        return new Ofx();
    }

    /**
     * Create an instance of {@link Ofxchart.XAxis }
     * 
     */
    public Ofxchart.XAxis createOfxchartXAxis() {
        return new Ofxchart.XAxis();
    }

    /**
     * Create an instance of {@link Wikiinjection.Wikicontent }
     * 
     */
    public Wikiinjection.Wikicontent createWikiinjectionWikicontent() {
        return new Wikiinjection.Wikicontent();
    }

    /**
     * Create an instance of {@link Color }
     * 
     */
    public Color createColor() {
        return new Color();
    }

    /**
     * Create an instance of {@link Ofxchart.YAxis }
     * 
     */
    public Ofxchart.YAxis createOfxchartYAxis() {
        return new Ofxchart.YAxis();
    }

    /**
     * Create an instance of {@link Ofxchartdata }
     * 
     */
    public Ofxchartdata createOfxchartdata() {
        return new Ofxchartdata();
    }

    /**
     * Create an instance of {@link Ofxgallery }
     * 
     */
    public Ofxgallery createOfxgallery() {
        return new Ofxgallery();
    }

    /**
     * Create an instance of {@link Ofxchart }
     * 
     */
    public Ofxchart createOfxchart() {
        return new Ofxchart();
    }

    /**
     * Create an instance of {@link Replacements }
     * 
     */
    public Replacements createReplacements() {
        return new Replacements();
    }

    /**
     * Create an instance of {@link Ofxgallery.Ofximage }
     * 
     */
    public Ofxgallery.Ofximage createOfxgalleryOfximage() {
        return new Ofxgallery.Ofximage();
    }

    /**
     * Create an instance of {@link Page }
     * 
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link Server }
     * 
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link Wikireplace }
     * 
     */
    public Wikireplace createWikireplace() {
        return new Wikireplace();
    }

    /**
     * Create an instance of {@link Ofxchartcontainer }
     * 
     */
    public Ofxchartcontainer createOfxchartcontainer() {
        return new Ofxchartcontainer();
    }

    /**
     * Create an instance of {@link Ofxchart.Size }
     * 
     */
    public Ofxchart.Size createOfxchartSize() {
        return new Ofxchart.Size();
    }

    /**
     * Create an instance of {@link Injections }
     * 
     */
    public Injections createInjections() {
        return new Injections();
    }

    /**
     * Create an instance of {@link Preprocessor }
     * 
     */
    public Preprocessor createPreprocessor() {
        return new Preprocessor();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Ofxchart.Title }
     * 
     */
    public Ofxchart.Title createOfxchartTitle() {
        return new Ofxchart.Title();
    }

    /**
     * Create an instance of {@link Ofxchart.Colors }
     * 
     */
    public Ofxchart.Colors createOfxchartColors() {
        return new Ofxchart.Colors();
    }

    /**
     * Create an instance of {@link Ofxchart.Grid }
     * 
     */
    public Ofxchart.Grid createOfxchartGrid() {
        return new Ofxchart.Grid();
    }

    /**
     * Create an instance of {@link Wikiinjection }
     * 
     */
    public Wikiinjection createWikiinjection() {
        return new Wikiinjection();
    }

}
