//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.09 at 04:46:15 PM MESZ 
//


package org.openfuxml.addon.wiki.data.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wikitag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ofxtag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "wikiinjection")
public class Wikiinjection {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String format;
    @XmlAttribute
    protected String wikitag;
    @XmlAttribute
    protected String ofxtag;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the wikitag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWikitag() {
        return wikitag;
    }

    /**
     * Sets the value of the wikitag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWikitag(String value) {
        this.wikitag = value;
    }

    /**
     * Gets the value of the ofxtag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfxtag() {
        return ofxtag;
    }

    /**
     * Sets the value of the ofxtag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfxtag(String value) {
        this.ofxtag = value;
    }

}
