//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 11:23:01 AM MEZ 
//


package org.openfuxml.renderer.data.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openfuxml.addon.wiki.data.jaxb.Preprocessor;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openfuxml.org/wiki}preprocessor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preprocessor"
})
@XmlRootElement(name = "wiki")
public class Wiki
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://www.openfuxml.org/wiki", required = true)
    protected Preprocessor preprocessor;

    /**
     * Gets the value of the preprocessor property.
     * 
     * @return
     *     possible object is
     *     {@link Preprocessor }
     *     
     */
    public Preprocessor getPreprocessor() {
        return preprocessor;
    }

    /**
     * Sets the value of the preprocessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preprocessor }
     *     
     */
    public void setPreprocessor(Preprocessor value) {
        this.preprocessor = value;
    }

    public boolean isSetPreprocessor() {
        return (this.preprocessor!= null);
    }

}
