//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 06:12:22 PM MESZ 
//


package org.openfuxml.content.ofx.table;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openfuxml.org/table}colSpec" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.openfuxml.org/table}head" minOccurs="0"/>
 *         &lt;element ref="{http://www.openfuxml.org/table}body"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "colSpec",
    "head",
    "body"
})
@XmlRootElement(name = "group")
public class Group
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<ColSpec> colSpec;
    protected Head head;
    @XmlElement(required = true)
    protected Body body;

    /**
     * Gets the value of the colSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the colSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColSpec }
     * 
     * 
     */
    public List<ColSpec> getColSpec() {
        if (colSpec == null) {
            colSpec = new ArrayList<ColSpec>();
        }
        return this.colSpec;
    }

    public boolean isSetColSpec() {
        return ((this.colSpec!= null)&&(!this.colSpec.isEmpty()));
    }

    public void unsetColSpec() {
        this.colSpec = null;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    public boolean isSetHead() {
        return (this.head!= null);
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Body }
     *     
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body }
     *     
     */
    public void setBody(Body value) {
        this.body = value;
    }

    public boolean isSetBody() {
        return (this.body!= null);
    }

}
