//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.25 at 04:53:27 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openfuxml.org/graph", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openfuxml.xml.addon.graph;
