//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b01-EA2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.14 at 08:54:11 AM MEZ 
//


package org.openfuxml.util.config.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.util.config.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.util.config.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Openfuxml }
     * 
     */
    public Openfuxml createOpenfuxml() {
        return new Openfuxml();
    }

    /**
     * Create an instance of {@link Dirs }
     * 
     */
    public Dirs createDirs() {
        return new Dirs();
    }

    /**
     * Create an instance of {@link Dirs.Dir }
     * 
     */
    public Dirs.Dir createDirsDir() {
        return new Dirs.Dir();
    }

    /**
     * Create an instance of {@link Files }
     * 
     */
    public Files createFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link Net }
     * 
     */
    public Net createNet() {
        return new Net();
    }

}
