//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.06 at 08:44:11 PM MESZ 
//


package org.openfuxml.content.ofx;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openfuxml.org}tableRow"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tableRow"
})
@XmlRootElement(name = "tableHead")
public class TableHead
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TableRow tableRow;

    /**
     * Gets the value of the tableRow property.
     * 
     * @return
     *     possible object is
     *     {@link TableRow }
     *     
     */
    public TableRow getTableRow() {
        return tableRow;
    }

    /**
     * Sets the value of the tableRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableRow }
     *     
     */
    public void setTableRow(TableRow value) {
        this.tableRow = value;
    }

    public boolean isSetTableRow() {
        return (this.tableRow!= null);
    }

}
