//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.13 at 09:36:17 PM MESZ 
//


package org.openfuxml.addon.wiki.data.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.addon.wiki.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.addon.wiki.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Wikicontainer }
     * 
     */
    public Wikicontainer createWikicontainer() {
        return new Wikicontainer();
    }

    /**
     * Create an instance of {@link Ofxgallery }
     * 
     */
    public Ofxgallery createOfxgallery() {
        return new Ofxgallery();
    }

    /**
     * Create an instance of {@link Wikireplace }
     * 
     */
    public Wikireplace createWikireplace() {
        return new Wikireplace();
    }

    /**
     * Create an instance of {@link Ofxchartdata }
     * 
     */
    public Ofxchartdata createOfxchartdata() {
        return new Ofxchartdata();
    }

    /**
     * Create an instance of {@link Ofxchartcontainer }
     * 
     */
    public Ofxchartcontainer createOfxchartcontainer() {
        return new Ofxchartcontainer();
    }

    /**
     * Create an instance of {@link Wikiinjection.Wikicontent }
     * 
     */
    public Wikiinjection.Wikicontent createWikiinjectionWikicontent() {
        return new Wikiinjection.Wikicontent();
    }

    /**
     * Create an instance of {@link Wikiinjection }
     * 
     */
    public Wikiinjection createWikiinjection() {
        return new Wikiinjection();
    }

    /**
     * Create an instance of {@link Ofxchart }
     * 
     */
    public Ofxchart createOfxchart() {
        return new Ofxchart();
    }

    /**
     * Create an instance of {@link Ofxgallery.Ofximage }
     * 
     */
    public Ofxgallery.Ofximage createOfxgalleryOfximage() {
        return new Ofxgallery.Ofximage();
    }

}
