//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.13 at 12:25:35 PM MESZ 
//


package org.openfuxml.content;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.content package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.content
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Table.Tgroup.Colspec }
     * 
     */
    public Table.Tgroup.Colspec createTableTgroupColspec() {
        return new Table.Tgroup.Colspec();
    }

    /**
     * Create an instance of {@link Table.Tgroup.Tbody }
     * 
     */
    public Table.Tgroup.Tbody createTableTgroupTbody() {
        return new Table.Tgroup.Tbody();
    }

    /**
     * Create an instance of {@link Table.Tgroup }
     * 
     */
    public Table.Tgroup createTableTgroup() {
        return new Table.Tgroup();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Listing }
     * 
     */
    public Listing createListing() {
        return new Listing();
    }

    /**
     * Create an instance of {@link Raw }
     * 
     */
    public Raw createRaw() {
        return new Raw();
    }

    /**
     * Create an instance of {@link AbsatzOhne }
     * 
     */
    public AbsatzOhne createAbsatzOhne() {
        return new AbsatzOhne();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Emphasis }
     * 
     */
    public Emphasis createEmphasis() {
        return new Emphasis();
    }

    /**
     * Create an instance of {@link Medienobjekt }
     * 
     */
    public Medienobjekt createMedienobjekt() {
        return new Medienobjekt();
    }

    /**
     * Create an instance of {@link Grafik }
     * 
     */
    public Grafik createGrafik() {
        return new Grafik();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Row.Entry }
     * 
     */
    public Row.Entry createRowEntry() {
        return new Row.Entry();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Medienobjekt.Objekttitel }
     * 
     */
    public Medienobjekt.Objekttitel createMedienobjektObjekttitel() {
        return new Medienobjekt.Objekttitel();
    }

    /**
     * Create an instance of {@link Table.Tgroup.Thead }
     * 
     */
    public Table.Tgroup.Thead createTableTgroupThead() {
        return new Table.Tgroup.Thead();
    }

}
