//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.10 at 04:27:23 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openfuxml.org/ofx", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openfuxml.content;
