//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.11 at 09:56:53 AM MESZ 
//


package org.openfuxml.addon.jsf.data.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.addon.jsf.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.addon.jsf.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Table.Tgroup }
     * 
     */
    public Table.Tgroup createTableTgroup() {
        return new Table.Tgroup();
    }

    /**
     * Create an instance of {@link Medienobjekt.Objekttitel }
     * 
     */
    public Medienobjekt.Objekttitel createMedienobjektObjekttitel() {
        return new Medienobjekt.Objekttitel();
    }

    /**
     * Create an instance of {@link Table.Tgroup.Thead }
     * 
     */
    public Table.Tgroup.Thead createTableTgroupThead() {
        return new Table.Tgroup.Thead();
    }

    /**
     * Create an instance of {@link Table.Tgroup.Colspec }
     * 
     */
    public Table.Tgroup.Colspec createTableTgroupColspec() {
        return new Table.Tgroup.Colspec();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link Renderer }
     * 
     */
    public Renderer createRenderer() {
        return new Renderer();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link FacesConfig.RenderKit }
     * 
     */
    public FacesConfig.RenderKit createFacesConfigRenderKit() {
        return new FacesConfig.RenderKit();
    }

    /**
     * Create an instance of {@link Listing }
     * 
     */
    public Listing createListing() {
        return new Listing();
    }

    /**
     * Create an instance of {@link Attribute.DeferredMethod }
     * 
     */
    public Attribute.DeferredMethod createAttributeDeferredMethod() {
        return new Attribute.DeferredMethod();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Row.Entry }
     * 
     */
    public Row.Entry createRowEntry() {
        return new Row.Entry();
    }

    /**
     * Create an instance of {@link Attribute.DeferredValue }
     * 
     */
    public Attribute.DeferredValue createAttributeDeferredValue() {
        return new Attribute.DeferredValue();
    }

    /**
     * Create an instance of {@link AbsatzOhne }
     * 
     */
    public AbsatzOhne createAbsatzOhne() {
        return new AbsatzOhne();
    }

    /**
     * Create an instance of {@link Metatag.Examples }
     * 
     */
    public Metatag.Examples createMetatagExamples() {
        return new Metatag.Examples();
    }

    /**
     * Create an instance of {@link Example }
     * 
     */
    public Example createExample() {
        return new Example();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Emphasis }
     * 
     */
    public Emphasis createEmphasis() {
        return new Emphasis();
    }

    /**
     * Create an instance of {@link Table.Tgroup.Tbody }
     * 
     */
    public Table.Tgroup.Tbody createTableTgroupTbody() {
        return new Table.Tgroup.Tbody();
    }

    /**
     * Create an instance of {@link FacesConfig }
     * 
     */
    public FacesConfig createFacesConfig() {
        return new FacesConfig();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Grafik }
     * 
     */
    public Grafik createGrafik() {
        return new Grafik();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link Metatag }
     * 
     */
    public Metatag createMetatag() {
        return new Metatag();
    }

    /**
     * Create an instance of {@link Medienobjekt }
     * 
     */
    public Medienobjekt createMedienobjekt() {
        return new Medienobjekt();
    }

    /**
     * Create an instance of {@link Taglib }
     * 
     */
    public Taglib createTaglib() {
        return new Taglib();
    }

}
