//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.14 at 06:33:06 AM MEZ 
//


package org.openfuxml.addon.chart.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openfuxml.org/chart}axisType"/>
 *         &lt;element name="dateTicker" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="timePeriod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.openfuxml.org/chart}label"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dateformat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autoRangIncludeNull" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "axisType",
    "dateTicker",
    "label"
})
@XmlRootElement(name = "axis")
public class Axis
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://www.openfuxml.org/chart", required = true)
    protected AxisType axisType;
    @XmlElement(required = true)
    protected List<Axis.DateTicker> dateTicker;
    @XmlElement(namespace = "http://www.openfuxml.org/chart", required = true)
    protected Label label;
    @XmlAttribute
    protected String code;
    @XmlAttribute
    protected String dateformat;
    @XmlAttribute
    protected Boolean autoRangIncludeNull;

    /**
     * Gets the value of the axisType property.
     * 
     * @return
     *     possible object is
     *     {@link AxisType }
     *     
     */
    public AxisType getAxisType() {
        return axisType;
    }

    /**
     * Sets the value of the axisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxisType }
     *     
     */
    public void setAxisType(AxisType value) {
        this.axisType = value;
    }

    public boolean isSetAxisType() {
        return (this.axisType!= null);
    }

    /**
     * Gets the value of the dateTicker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateTicker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateTicker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Axis.DateTicker }
     * 
     * 
     */
    public List<Axis.DateTicker> getDateTicker() {
        if (dateTicker == null) {
            dateTicker = new ArrayList<Axis.DateTicker>();
        }
        return this.dateTicker;
    }

    public boolean isSetDateTicker() {
        return ((this.dateTicker!= null)&&(!this.dateTicker.isEmpty()));
    }

    public void unsetDateTicker() {
        this.dateTicker = null;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    public boolean isSetLabel() {
        return (this.label!= null);
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    public boolean isSetCode() {
        return (this.code!= null);
    }

    /**
     * Gets the value of the dateformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateformat() {
        return dateformat;
    }

    /**
     * Sets the value of the dateformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateformat(String value) {
        this.dateformat = value;
    }

    public boolean isSetDateformat() {
        return (this.dateformat!= null);
    }

    /**
     * Gets the value of the autoRangIncludeNull property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoRangIncludeNull() {
        return autoRangIncludeNull;
    }

    /**
     * Sets the value of the autoRangIncludeNull property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoRangIncludeNull(boolean value) {
        this.autoRangIncludeNull = value;
    }

    public boolean isSetAutoRangIncludeNull() {
        return (this.autoRangIncludeNull!= null);
    }

    public void unsetAutoRangIncludeNull() {
        this.autoRangIncludeNull = null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="timePeriod" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DateTicker
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute
        protected String timePeriod;
        @XmlAttribute
        protected String format;

        /**
         * Gets the value of the timePeriod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimePeriod() {
            return timePeriod;
        }

        /**
         * Sets the value of the timePeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimePeriod(String value) {
            this.timePeriod = value;
        }

        public boolean isSetTimePeriod() {
            return (this.timePeriod!= null);
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

        public boolean isSetFormat() {
            return (this.format!= null);
        }

    }

}
